name: Tests

on:
  push:
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pip install .
          pytest --cov=inka --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: GitHub

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: mypy
        run: |
          pip install mypy types-click types-requests
          mypy --python-version=3.10 src/

      - name: flake8
        run: |
          pip install flake8
          flake8 src/ tests/

      - name: black
        uses: psf/black@stable

      - name: isort
        run: |
          pip install isort
          isort . --check --diff
